# OpenWebUI - Configuração Original Otimizada para APIs Externas

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - "openwebui-network"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  openwebui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openwebui
    restart: unless-stopped
    volumes:
      - ./openwebui-data:/app/backend/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=true
      - ENABLE_SIGNUP=true
      - DEFAULT_USER_ROLE=user
      - ENABLE_OPENAI_API=true
      - ENABLE_OLLAMA_API=false
      - OPENAI_API_BASE_URL=http://host.docker.internal:8001/v1
      - OPENAI_API_BASE_URLS=http://host.docker.internal:8001/v1
      - OPENAI_API_KEY=dummy-key
      - OPENAI_API_KEYS=dummy-key
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - "keycloak-network"
      - "openwebui-network"

networks:
  keycloak-network:
    external: true
    name: doctul_open-webui_keycloak-network
  openwebui-network:
    driver: bridge

volumes:
  openwebui-data:
    driver: local
  redis-data:
    driver: local
