version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    ports:
      - "9090:8080"
    command: 
      - start-dev
      - --http-port=8080
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-network

volumes:
  keycloak_data:

networks:
  keycloak-network:
    driver: bridge
