# OpenWebUI - Configuração Original Otimizada para APIs Externas

services:
  openwebui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openwebui
    restart: unless-stopped
    volumes:
      - openwebui-data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      # ========================================
      # CONFIGURAÇÕES DE API EXTERNA
      # ========================================
      
      # Desabilitar Ollama e habilitar OpenAI API
      - ENABLE_OLLAMA_API=false
      - ENABLE_OPENAI_API=true
      
      # Configuração da API principal (modelo na porta 8001)
      - OPENAI_API_BASE_URL=http://host.docker.internal:8001/v1
      - OPENAI_API_BASE_URLS=http://host.docker.internal:8001/v1
      - OPENAI_API_KEY=none
      - OPENAI_API_KEYS=none
      
      # ========================================
      # CONFIGURAÇÕES RAG/EMBEDDING
      # ========================================
      
      # Configuração RAG/Embedding (modelo na porta 8002)
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_EMBEDDING_MODEL=intfloat/multilingual-e5-base
      - RAG_OPENAI_API_BASE_URL=http://host.docker.internal:8002/v1
      - RAG_OPENAI_API_KEY=none
      - RAG_EMBEDDING_BATCH_SIZE=32
      
      # ========================================
      # CONFIGURAÇÕES BÁSICAS
      # ========================================
      
      - WEBUI_SECRET_KEY=your-secret-key-change-this-in-production
      - PORT=8080
      - DATA_DIR=/app/backend/data
      - DOCKER=true
      
      # ========================================
      # CONFIGURAÇÃO HÍBRIDA: ACESSO ANÔNIMO + KEYCLOAK
      # ========================================
      
      # Acesso anônimo como usuário limitado
      - WEBUI_AUTH=false
      - DEFAULT_USER_ROLE=user
      - ANONYMOUS_USER_ENABLED=true
      
      # Keycloak OAuth (para usuários autenticados)
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_CLIENT_ID=open-webui
      - OAUTH_CLIENT_SECRET=nyjX5oePLoMRnPNMik17dKEdlLYUnCCw
      - OPENID_PROVIDER_URL=http://keycloak:8080/realms/openwebui/.well-known/openid-configuration
      - OAUTH_PROVIDER_NAME=Keycloak Login
      - OPENID_REDIRECT_URI=http://localhost:3000/oauth/oidc/callback
      
      # Controle de grupos via Keycloak
      - ENABLE_OAUTH_GROUP_MANAGEMENT=true
      - ENABLE_OAUTH_GROUP_CREATION=true
      - OAUTH_GROUPS_CLAIM=groups
      
      # Permissões para usuários anônimos (limitadas)
      - USER_PERMISSIONS_CHAT_DELETION=false
      - USER_PERMISSIONS_CHAT_EDITING=false
      - ENABLE_COMMUNITY_SHARING=false
      - ENABLE_ADMIN_EXPORT=false
      - ENABLE_API_KEY=false
      - JWT_EXPIRES_IN=-1
      
      # Configurações para acesso direto
      - WEBUI_SESSION_COOKIE_SECURE=false
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      
      # ========================================
      # FUNCIONALIDADES BÁSICAS
      # ========================================
      
      - ENABLE_CHANNELS=true
      - ENABLE_NOTES=true
      - ENABLE_COMMUNITY_SHARING=true
      - ENABLE_MESSAGE_RATING=true
      - ENABLE_USER_WEBHOOKS=false
      
      # ========================================
      # CONFIGURAÇÕES RAG ADICIONAIS
      # ========================================
      
      - RAG_TOP_K=5
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=100
      - PDF_EXTRACT_IMAGES=false
      - ENABLE_RAG_WEB_SEARCH=false
      - ENABLE_RAG_LOCAL_WEB_FETCH=true
      - ENABLE_RAG_HYBRID_SEARCH=true
      
      # ========================================
      # LOGS E DEBUG
      # ========================================
      
      - GLOBAL_LOG_LEVEL=INFO
      - RAG_LOG_LEVEL=DEBUG
      - OPENAI_LOG_LEVEL=DEBUG
      - MODELS_LOG_LEVEL=INFO
      
      # ========================================
      # CONFIGURAÇÕES DE SEGURANÇA
      # ========================================
      
      - WEBUI_SESSION_COOKIE_SECURE=false
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      - ENABLE_COMPRESSION_MIDDLEWARE=true
      
      # ========================================
      # OUTRAS CONFIGURAÇÕES IMPORTANTES
      # ========================================
      
      - ENABLE_WEBSOCKET_SUPPORT=true
      - ENABLE_VERSION_UPDATE_CHECK=true
      - BYPASS_MODEL_ACCESS_CONTROL=false
      - SAFE_MODE=false
      - ENV=prod
      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - openwebui-network

volumes:
  openwebui-data:
    name: openwebui-data

networks:
  openwebui-network:
    driver: bridge
    name: openwebui-network
